// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etvrexlzwnhdtvirgunb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0dnJleGx6d25oZHR2aXJndW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NzE2NzcsImV4cCI6MjA3MzU0NzY3N30.qmp5Eh0q_oSOtBN0E9GpwX1HvEMcyZOPb_4Iwlrg0vs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});